### ISSUE TITLE
[Development] Add .clang-format file

### ISSUE THREAD

**Issue by nobounce** [aristocratos/btop#573]
This project should use a code formatting tool like [clang-format](https://clang.llvm.org/docs/ClangFormat.html). Clang-format allows to format the code according to guidelines put in a `.clang-format`-file.

Why consistency?
Pros
* Easy readability of the code base
* Makes it easier for new contributors to look around in the source code
* A lot of people consider this a best practice, for example [Google](https://google.github.io/styleguide/cppguide.html#Goals)
* Avoids further discussion about how an `if`-statement should look like, if it is already determined

Cons
* I seriously don't know, hit me up

`clang-format` helps to enforce consistent code style and readable code. Any developer can just write code in the style they want and with the click of a button or a single command the code is properly adjusted
[You read more code than you write](https://bayrhammer-klaus.medium.com/you-spend-much-more-time-reading-code-than-writing-code-bc953376fe19), and if we can read it faster, we can spend more time writing new code.

Even if you don't mind or care, this probably makes it easier for others to dig into the source code.
And if someone opens a pull request with code not according to the project's style, it just a matter of "Please run clang-format over that" and it's done. Simple as that.
And in the end, it's just a file. It's has no impact on the users but helps developers which use that tool.

**Comment by nobounce** [comment]
This might also be interesting for a consistent style guide:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
https://github.com/cpp-best-practices/cppbestpractices/blob/master/03-Style.md#style

**Comment by nobounce** [comment]
```
---
BasedOnStyle: LLVM
# Language
Language: Cpp
AccessModifierOffset: -4
AlignAfterOpenBracket: BlockIndent
AllowShortCaseLabelsOnASingleLine: true
AllowShortIfStatementsOnASingleLine: AllIfsAndElse
AllowShortLoopsOnASingleLine: true
AlwaysBreakBeforeMultilineStrings: true
BinPackArguments: false
BraceWrapping:
  BeforeCatch: true
  BeforeElse: true
BreakBeforeBraces: Custom
ColumnLimit: 120
IndentCaseLabels: true
IndentPPDirectives: BeforeHash
IndentWidth: 4
NamespaceIndentation: All
PointerAlignment: Left
QualifierAlignment: Left
ReferenceAlignment: Left
Standard: c++20
TabWidth: 4
UseTab: Always
```

This could be a sample file which follows the general style of btop's code and adjust smaller parts which are not consistent.
